
    services:
      angular:
        image: mi-app-angular
        build:
          context: ./FrontEnd/person-crud-app
        ports:
          - "4201:80"
        depends_on:
          - dotnet

      dotnet:
        image: mi-app-dotnet
        build:
          context: ./CRUDPersonCleanArchitecture/CRUDPersonCleanArchitecture
        ports:
          - "5000:80"
        depends_on:
          - db
      db:
        image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: 1234*
          MYSQL_DATABASE: PersonCatalogDB
        ports:
          - "33061:3306"